// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

let version = "1.18.2"
let packageLibraryName = "Compatibility"

#if canImport(PackageDescription)
import PackageDescription
#endif
#if canImport(AppleProductTypes)
import AppleProductTypes
#endif

var products = [
    Product.library(
        name: "\(packageLibraryName) Library",
        targets: [packageLibraryName]
    ),
]

var targets = [
    Target.target(
        name: packageLibraryName,
        dependencies: [],
        path: "Sources",
        exclude: ["CompatibilityTesting"]
    ),
]

var platforms: [SupportedPlatform] = [
    .macOS("10.10"),
    .tvOS("11"),
    .watchOS("4"),
]

#if SwiftPlaygrounds || canImport(PlaygroundSupport)
platforms += [.iOS("15.2")]
#else
platforms += [.iOS("11")]
#endif

#if compiler(>=5.9) && os(visionOS)
platforms += [.visionOS("1.0")]
#endif

#if canImport(AppleProductTypes)
import AppleProductTypes

let executableTargetName = "\(packageLibraryName)TestAppModule"

#if SwiftPlaygrounds || canImport(PlaygroundSupport)
let appName = "\(packageLibraryName) Playground"
#else
let appName = "\(packageLibraryName) App"
#endif

products += [
    .iOSApplication(
        name: appName,
        targets: [executableTargetName],
        teamIdentifier: "3QPV894C33",
        displayVersion: version,
        bundleVersion: "1",
        appIcon: .asset("AppIcon"),
        accentColor: .presetColor(.orange),
        supportedDeviceFamilies: [.pad, .phone],
        supportedInterfaceOrientations: [
            .portrait,
            .landscapeRight,
            .landscapeLeft,
            .portraitUpsideDown(.when(deviceFamilies: [.pad])),
        ],
        capabilities: [.outgoingNetworkConnections()],
        appCategory: .developerTools
    ),
]

targets += [
    .executableTarget(
        name: executableTargetName,
        dependencies: [.init(stringLiteral: packageLibraryName)],
        path: "Development",
        exclude: ["Resources", "CompatibilityTests", "CompatibilitySwiftPMTests", "compatibilityCLI"],
        resources: []
    ),
]
#endif

// Test-only products remain in the same package and therefore appear in the same .swiftpm project.
#if !SwiftPlaygrounds && !canImport(PlaygroundSupport)
products += [
    .library(
        name: "Compatibility Testing Library",
        targets: ["CompatibilityTesting"]
    ),
    .executable(
        name: "compatibilityCLI",
        targets: ["compatibilityCLI"]
    ),
]

targets += [
    .target(
        name: "CompatibilityTesting",
        dependencies: [.init(stringLiteral: packageLibraryName)],
        path: "Sources/CompatibilityTesting"
    ),
    .executableTarget(
        name: "compatibilityCLI",
        dependencies: [.init(stringLiteral: packageLibraryName)],
        path: "Development/compatibilityCLI"
    ),
    .testTarget(
        name: "\(packageLibraryName)Tests",
        dependencies: [
            .init(stringLiteral: packageLibraryName),
            "CompatibilityTesting",
        ],
        path: "Development/CompatibilityTests",
        exclude: ["CompatibilityTest.xctestplan"]
    ),
]
#endif

let package = Package(
    name: packageLibraryName,
    platforms: platforms,
    products: products,
    dependencies: [],
    targets: targets
)
